pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "status-success=test-build-and-deploy"
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: automatic merge without review
    conditions:
      - base=master
      - "status-success=test-build-and-deploy"
      - label=no-review-needed
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
