defaults:
  actions:
    queue:
      name: default
      method: rebase

queue_rules:
  - name: default
    conditions:
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
    speculative_checks: 5

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - check-success=GitGuardian Security Checks
      - check-success=Semantic Pull Request
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
  - name: automatic merge for hotfix
    conditions:
      - base=master
      - author=@devs
      - check-success=GitGuardian Security Checks
      - check-success=Semantic Pull Request
      - body~=(?m)^Fixes MERGIFY-ENGINE-
      - label=hotfix
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        priority: high
  - name: automatic merge from dependabot
    conditions:
      - check-success=GitGuardian Security Checks
      - check-success=Semantic Pull Request
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        priority: low
  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: False
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - label!=work-in-progress
      - -merged
      - -closed
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
    actions:
      request_reviews:
        teams:
          - devs
  - name: warn on no Sentry
    conditions:
      - -body~=(?m)^Fixes MERGIFY-ENGINE-
      - label=hotfix
    actions:
      comment:
        message: Your pull request is a hotfix but does not fix a Sentry issue. 🤔
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: warn on CI failure for hotfix
    conditions:
      - label=hotfix
      - "#check-failure>0"
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺
