pull_request_rules:
  - name: automatic merge
    conditions:
      - status-success=Travis CI - Pull Request
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: automatic merge without review
    conditions:
      - status-success=Travis CI - Pull Request
      - label=no-review-needed
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
