pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: auto remove wip
    conditions:
      - "-title~=^(wip|WIP).*"
    actions:
      label:
        remove: ["work-in-progress"]

