defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message: title+body
    squash:
      commit_message: first-commit

queue_rules:
  - name: hotfix
    conditions:
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
    speculative_checks: 5

  - name: default
    conditions:
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: lowprio
    conditions:
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - schedule=Mon-Fri 09:30-17:00[Europe/Paris]
    speculative_checks: 3
    batch_size: 5

pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - base=main
      - author=@devs
      - check-success=semantic-pull-request
      - body~=(?m)^Fixes MERGIFY-ENGINE-
      - label=hotfix
      - "#changes-requested-reviews-by=0"
      - "#commits=1"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: hotfix

  - name: automatic merge
    conditions:
      - base=main
      - check-success=semantic-pull-request
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#commits=1"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:

  - name: automatic merge from dependabot
    conditions:
      - check-success=semantic-pull-request
      - check-success=requirements
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
      - "#commits=1"
    actions:
      queue:
        name: lowprio

  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: False
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - label!=work-in-progress
      - -merged
      - -closed
      - check-success=requirements
      - check-success=pep8
      - check-success=py39
      - check-success=docs
      - check-success=docker
      - check-success=heroku
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
    actions:
      request_reviews:
        teams:
          - devs
  - name: warn on no Sentry
    conditions:
      - -body~=(?m)^Fixes MERGIFY-ENGINE-
      - label=hotfix
    actions:
      comment:
        message: Your pull request is a hotfix but does not fix a Sentry issue. 🤔
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: warn on CI failure for hotfix
    conditions:
      - label=hotfix
      - "#check-failure>0"
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺
