pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "status-success=ci/circleci: requirements"
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: docs"
      - "status-success=ci/circleci: build-docker-image"
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: automatic merge without review
    conditions:
      - base=master
      - "status-success=ci/circleci: requirements"
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: docs"
      - "status-success=ci/circleci: build-docker-image"
      - label=no-review-needed
      - label!=work-in-progress
      - label!=manual merge
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: automatic merge from dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label!=work-in-progress
      - label!=manual merge
      - "status-success=ci/circleci: requirements"
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: docs"
      - "status-success=ci/circleci: build-docker-image"
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]
  - name: request review
    conditions:
      - -author~=^dependabot(|-preview)\[bot\]$
      - label!=work-in-progress
    actions:
      request_reviews:
        teams:
          - devs
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict :(
