extends: default
ignore: |
  .git
  .tox
  docs/node_modules
  installer/node_modules
rules:
  document-start: disable
  truthy: disable
  comments:
    level: error
  comments-indentation:
    level: error
  line-length:
    max: 110
