version: "3"

services:
  storage:
    env_file: ${ENV}.env
    image: redis:alpine
    volumes:
      - redis-storage:/data

  celery:
    env_file: ${ENV}.env
    image: redis:alpine
    volumes:
      - redis-celery:/data

  wsgi:
    env_file: ${ENV}.env
    image: mergifyio/engine:latest
    depends_on:
      - storage
      - celery
    ports:
     - "8802:8802"
    command: uwsgi --socket 127.0.0.1:8802 --master --enable-threads --die-on-term --processes 4 --threads 4 --lazy-apps --thunder-lock --plugin python3 --wsgi-file /app/mergify_engine/wsgi.py
    environment:
      - MERGIFYENGINE_STORAGE_URL=redis://storage:6379
      - MERGIFYENGINE_CELERY_BROKER_URL=redis://celery:6379

  engine:
    env_file: ${ENV}.env
    image: mergifyio/engine:latest
    depends_on:
      - storage
      - celery
    command: celery worker -A mergify_engine.worker -X legacy-engine-v1 -P gevent --autoscale=10,1
    environment:
      - MERGIFYENGINE_STORAGE_URL=redis://storage:6379
      - MERGIFYENGINE_CELERY_BROKER_URL=redis://celery:6379

  engine-beat:
    env_file: ${ENV}.env
    image: mergifyio/engine:latest
    depends_on:
      - storage
      - celery
    volumes:
      - celery-beat:/data
    command: celery worker -A mergify_engine.worker -B --schedule-filename /data/celerybeat-schedule.db
    environment:
      - MERGIFYENGINE_STORAGE_URL=redis://storage:6379
      - MERGIFYENGINE_CELERY_BROKER_URL=redis://celery:6379

  engine-exporter:
    env_file: ${ENV}.env
    image: mergifyio/engine:latest
    depends_on:
      - storage
      - celery
    ports:
      - 8889:8889
    command: mergify-exporter --port 8889
    environment:
      - MERGIFYENGINE_STORAGE_URL=redis://storage:6379
      - MERGIFYENGINE_CELERY_BROKER_URL=redis://celery:6379

  celery-exporter:
    image: zerok/celery-prometheus-exporter:latest-celery4
    depends_on:
      - celery
    command: --broker=redis://celery:6379

  # Never scale that one
  engine-legacy:
    env_file: ${ENV}.env
    image: mergifyio/engine:latest
    depends_on:
      - storage
      - celery
    command: celery worker -A mergify_engine.worker -Q legacy-engine-v1 --concurrency 1
    environment:
      - MERGIFYENGINE_STORAGE_URL=redis://storage:6379
      - MERGIFYENGINE_CELERY_BROKER_URL=redis://celery:6379

volumes:
  redis-celery:
  redis-storage:
  celery-beat:
