---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files: []
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
    labels:
      alias: Prometheus
- job_name: mergify
  static_configs:
  - targets:
    - celery-exporter:8888
    - engine-exporter:8889
    labels:
      alias: Mergify
- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      alias: Node
