{
 "title": "Mergify",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Installations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(installations)" }
   ]
  },
  {
   "title": "Installations (Subscribed)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(installations{subscribed=\"True\"})"
    }
   ]
  },
  {
   "title": "MRR",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(5 + clamp_min(users_per_installation{subscribed=\"True\"} - 5, 0) * 2)"
    }
   ]
  },
  {
   "title": "MRR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(5 + clamp_min(users_per_installation{subscribed=\"True\"} - 5, 0) * 2)"
    }
   ]
  },
  {
   "title": "Users per installation (subscribed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Users" }
   ],
   "targets": [
    {
     "expr": "sum(users_per_installation{subscribed=\"True\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "users_per_installation{subscribed=\"True\"}",
     "legendFormat": "{{account}} "
    }
   ]
  },
  {
   "title": "Users per installation (free)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Users" }
   ],
   "targets": [
    {
     "expr": "sum(users_per_installation{subscribed=\"False\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "users_per_installation{subscribed=\"False\"}",
     "legendFormat": "{{account}} "
    }
   ]
  },
  {
   "title": "Repositories per installation (subscribed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Repositories" }
   ],
   "targets": [
    {
     "expr": "sum (repositories_per_installation{subscribed=\"True\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (account) (repositories_per_installation{subscribed=\"True\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Repositories per installation (free)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Repositories" }
   ],
   "targets": [
    {
     "expr": "sum  (repositories_per_installation{subscribed=\"False\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (account) (repositories_per_installation{subscribed=\"False\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Repositories per installation (Org+free+private)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Repositories" }
   ],
   "targets": [
    {
     "expr": "sum by (account) (repositories_per_installation{subscribed=\"False\", private=\"True\", type=\"Organization\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Repositories per installation (really configured)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Repositories" }
   ],
   "targets": [
    {
     "expr": "sum(repositories_per_installation{configured=\"True\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (account) (repositories_per_installation{configured=\"True\"})",
     "legendFormat": "{{account}}"
    }
   ]
  }
 ]
}