{
 "title": "Tasks monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "INTERVAL",
    "label": "Rolling rate interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Pull requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pull request" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.pull_request_opened\", state=\"SUCCESS\"}[$INTERVAL])",
     "legendFormat": "Opened"
    },
    {
     "expr": "rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.pull_request_merged\", state=\"SUCCESS\"}[$INTERVAL])",
     "legendFormat": "Merged"
    },
    {
     "expr": "rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.pull_request_merged_by_mergify\", state=\"SUCCESS\"}[$INTERVAL])",
     "legendFormat": "Merged by Mergify"
    }
   ]
  },
  {
   "title": "Event filter runtime (filter_and_dispatch)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_runtime_bucket{name=~\"mergify_engine.tasks.github_events.job_filter_and_dispatch\",le=~\"0.05|0.5|1.0|2.5|5.0|\\\\+Inf\"}[$INTERVAL])",
     "legendFormat": "< {{le}}"
    }
   ]
  },
  {
   "title": "Engine base runtime (engine.run)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_runtime_bucket{name=~\"mergify_engine.tasks.engine.run\",le=~\"0.05|0.5|1.0|2.5|5.0|\\\\+Inf\"}[$INTERVAL])",
     "legendFormat": "< {{le}}"
    }
   ]
  },
  {
   "title": "GitHub events per seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_by_name{name=\"mergify_engine.tasks.github_events.job_filter_and_dispatch\"}[$INTERVAL]))",
     "legendFormat": "Events received"
    },
    {
     "expr": "sum(rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.run\"}[$INTERVAL]))",
     "legendFormat": "Events used"
    },
    {
     "expr": "sum(rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.run\", state=\"FAILURE\"}[$INTERVAL]))",
     "legendFormat": "Events failed"
    },
    {
     "expr": "sum(rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.v1._handle\"}[$INTERVAL]))",
     "legendFormat": "Events for v1"
    },
    {
     "expr": "sum(rate(celery_tasks_by_name{name=\"mergify_engine.tasks.engine.v2.handle\"}[$INTERVAL]))",
     "legendFormat": "Events for v2"
    }
   ]
  },
  {
   "title": "Engine v1 runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_runtime_bucket{name=~\"mergify_engine.tasks.engine.v1._handle\",le=~\"0.05|0.5|1.0|2.5|5.0|\\\\+Inf\"}[$INTERVAL])",
     "legendFormat": "< {{le}}"
    }
   ]
  },
  {
   "title": "Engine v2 runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_runtime_bucket{name=~\"mergify_engine.tasks.engine.v2.handle\",le=~\"0.05|0.5|1.0|2.5|5.0|\\\\+Inf\"}[$INTERVAL])",
     "legendFormat": "< {{le}}"
    }
   ]
  },
  {
   "title": "Celery latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(celery_task_latency_bucket{le=~\"\\\\+Inf|5.0|5.0|0.5|0.05|0.01|0.005\"}[$INTERVAL])",
     "legendFormat": "Latency < {{le}}"
    }
   ]
  }
 ]
}