name: Clifus
permissions: write-all

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clifus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: pip install PyYAML

      - name: Clifus
        id: clifus
        run: |
          ./tools/clifus.py -c ./.github/clifus.yml
          echo "::set-output name=PYTHON_VERSION::$(cat runtime.txt | cut -d- -f2)"

      - name: Create the Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          title: "chore: bump python version to ${{ steps.clifus.outputs.PYTHON_VERSION }}"
          body: This is an automated bump of python version to ${{ steps.clifus.outputs.PYTHON_VERSION }}
          branch: python-version-upgrade
          base: main
          labels: |
            python
            dependencies

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
